Resources:
  lambdaaServiceRole9E3E4538:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CDK-MonoRepo-Frontend/lambda-a/ServiceRole/Resource
  lambdaa278BDC98:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters40cc5351492b96cf5647611b16a3dd2326813cf5fb7b3508c703075d9b44dc94S3Bucket6C723BA0
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters40cc5351492b96cf5647611b16a3dd2326813cf5fb7b3508c703075d9b44dc94S3VersionKey2AC36793
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters40cc5351492b96cf5647611b16a3dd2326813cf5fb7b3508c703075d9b44dc94S3VersionKey2AC36793
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - lambdaaServiceRole9E3E4538
          - Arn
      Runtime: nodejs12.x
      FunctionName: lambda-a
      MemorySize: 256
    DependsOn:
      - lambdaaServiceRole9E3E4538
    Metadata:
      aws:cdk:path: CDK-MonoRepo-Frontend/lambda-a/Resource
      aws:asset:path: /Users/sive/Documents/Training/serverless/cdk-monorepo-example/cdk-monorepo-example-frontend-2/packages/lambda-a/dist
      aws:asset:property: Code
  WebsiteBucket75C24D94:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CDK-MonoRepo-Frontend/WebsiteBucket/Resource
  WebsiteBucketPolicyE10E3262:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: WebsiteBucket75C24D94
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal: "*"
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - WebsiteBucket75C24D94
                      - Arn
                  - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: CDK-MonoRepo-Frontend/WebsiteBucket/Policy/Resource
  DeployWebsiteCustomResourceD116527B:
    Type: Custom::CDKBucketDeployment
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C81C01536
          - Arn
      SourceBucketNames:
        - Ref: AssetParameters610c0efb50061b33b7bcb1d8eb49da576a7fe155e1a0810222f09c3a767f5d49S3BucketE1D948C9
      SourceObjectKeys:
        - Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters610c0efb50061b33b7bcb1d8eb49da576a7fe155e1a0810222f09c3a767f5d49S3VersionKeyD7AA2033
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters610c0efb50061b33b7bcb1d8eb49da576a7fe155e1a0810222f09c3a767f5d49S3VersionKeyD7AA2033
      DestinationBucketName:
        Ref: WebsiteBucket75C24D94
      Prune: true
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: CDK-MonoRepo-Frontend/DeployWebsite/CustomResource/Default
  CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CDK-MonoRepo-Frontend/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/ServiceRole/Resource
  CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRoleDefaultPolicy88902FDF:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Ref: AssetParameters610c0efb50061b33b7bcb1d8eb49da576a7fe155e1a0810222f09c3a767f5d49S3BucketE1D948C9
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":s3:::"
                    - Ref: AssetParameters610c0efb50061b33b7bcb1d8eb49da576a7fe155e1a0810222f09c3a767f5d49S3BucketE1D948C9
                    - /*
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject*
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - WebsiteBucket75C24D94
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - WebsiteBucket75C24D94
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRoleDefaultPolicy88902FDF
      Roles:
        - Ref: CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265
    Metadata:
      aws:cdk:path: CDK-MonoRepo-Frontend/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/ServiceRole/DefaultPolicy/Resource
  CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C81C01536:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersc9ac4b3b65f3510a2088b7fd003de23d2aefac424025eb168725ce6769e3c176S3Bucket77147E20
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc9ac4b3b65f3510a2088b7fd003de23d2aefac424025eb168725ce6769e3c176S3VersionKey4253216F
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersc9ac4b3b65f3510a2088b7fd003de23d2aefac424025eb168725ce6769e3c176S3VersionKey4253216F
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265
          - Arn
      Runtime: python3.6
      Timeout: 900
    DependsOn:
      - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRoleDefaultPolicy88902FDF
      - CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756CServiceRole89A01265
    Metadata:
      aws:cdk:path: CDK-MonoRepo-Frontend/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/Resource
      aws:asset:path: /Users/sive/Documents/Training/serverless/cdk-monorepo-example/cdk-monorepo-example-frontend-2/node_modules/@aws-cdk/aws-s3-deployment/lambda/bundle.zip
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.78.0,@aws-cdk/assets=1.75.0,@aws-cdk/aws-applicationautoscaling=1.75.0,@aws-cdk/aws-autoscaling-common=1.75.0,@aws-cdk/aws-cloudwatch=1.75.0,@aws-cdk/aws-codeguruprofiler=1.75.0,@aws-cdk/aws-ec2=1.75.0,@aws-cdk/aws-events=1.75.0,@aws-cdk/aws-iam=1.75.0,@aws-cdk/aws-kms=1.75.0,@aws-cdk/aws-lambda=1.75.0,@aws-cdk/aws-logs=1.75.0,@aws-cdk/aws-s3=1.75.0,@aws-cdk/aws-s3-assets=1.75.0,@aws-cdk/aws-s3-deployment=1.75.0,@aws-cdk/aws-sqs=1.75.0,@aws-cdk/aws-ssm=1.75.0,@aws-cdk/cloud-assembly-schema=1.75.0,@aws-cdk/core=1.75.0,@aws-cdk/cx-api=1.75.0,@aws-cdk/region-info=1.75.0,jsii-runtime=node.js/v14.14.0
    Metadata:
      aws:cdk:path: CDK-MonoRepo-Frontend/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters40cc5351492b96cf5647611b16a3dd2326813cf5fb7b3508c703075d9b44dc94S3Bucket6C723BA0:
    Type: String
    Description: S3 bucket for asset "40cc5351492b96cf5647611b16a3dd2326813cf5fb7b3508c703075d9b44dc94"
  AssetParameters40cc5351492b96cf5647611b16a3dd2326813cf5fb7b3508c703075d9b44dc94S3VersionKey2AC36793:
    Type: String
    Description: S3 key for asset version "40cc5351492b96cf5647611b16a3dd2326813cf5fb7b3508c703075d9b44dc94"
  AssetParameters40cc5351492b96cf5647611b16a3dd2326813cf5fb7b3508c703075d9b44dc94ArtifactHashEA2684C7:
    Type: String
    Description: Artifact hash for asset "40cc5351492b96cf5647611b16a3dd2326813cf5fb7b3508c703075d9b44dc94"
  AssetParametersc9ac4b3b65f3510a2088b7fd003de23d2aefac424025eb168725ce6769e3c176S3Bucket77147E20:
    Type: String
    Description: S3 bucket for asset "c9ac4b3b65f3510a2088b7fd003de23d2aefac424025eb168725ce6769e3c176"
  AssetParametersc9ac4b3b65f3510a2088b7fd003de23d2aefac424025eb168725ce6769e3c176S3VersionKey4253216F:
    Type: String
    Description: S3 key for asset version "c9ac4b3b65f3510a2088b7fd003de23d2aefac424025eb168725ce6769e3c176"
  AssetParametersc9ac4b3b65f3510a2088b7fd003de23d2aefac424025eb168725ce6769e3c176ArtifactHash4E343C6C:
    Type: String
    Description: Artifact hash for asset "c9ac4b3b65f3510a2088b7fd003de23d2aefac424025eb168725ce6769e3c176"
  AssetParameters610c0efb50061b33b7bcb1d8eb49da576a7fe155e1a0810222f09c3a767f5d49S3BucketE1D948C9:
    Type: String
    Description: S3 bucket for asset "610c0efb50061b33b7bcb1d8eb49da576a7fe155e1a0810222f09c3a767f5d49"
  AssetParameters610c0efb50061b33b7bcb1d8eb49da576a7fe155e1a0810222f09c3a767f5d49S3VersionKeyD7AA2033:
    Type: String
    Description: S3 key for asset version "610c0efb50061b33b7bcb1d8eb49da576a7fe155e1a0810222f09c3a767f5d49"
  AssetParameters610c0efb50061b33b7bcb1d8eb49da576a7fe155e1a0810222f09c3a767f5d49ArtifactHash6D26B93A:
    Type: String
    Description: Artifact hash for asset "610c0efb50061b33b7bcb1d8eb49da576a7fe155e1a0810222f09c3a767f5d49"
Outputs:
  WebsiteAddress:
    Value:
      Fn::GetAtt:
        - WebsiteBucket75C24D94
        - WebsiteURL
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

